### ISSUE TITLE
[enhancement] Add filter to the log output

### ISSUE THREAD

**Issue by samuraii** [lexmartinez/logcat-viewer#1]
I just run your app and I like it's simplicity, but this would be great if there was a way to filter te logs. By PID, and Message substring.

**Comment by lexmartinez** [comment]
Hey @samuraii, sorry by the late answer, the past week was a madness! i just release the 1.1.0 version, with filters and exporting features.. thanks for suggestions!

**Comment by samuraii** [comment]
great, many thanks
